name: build
on:
  push:
    branches-ignore:
      - main
permissions:
  contents: write
jobs:
  build_linux:
    name: Verify Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Download Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.10'
      - name: Download Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.19.0'
      - name: Download Protoc Compiler
        run: sudo apt-get install -y protobuf-compiler
      - name: Compile Proto
        run: export HATCHI_HOME=$GITHUB_WORKSPACE && ./proto/compile
        shell: bash
      - name: Build Flutter
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          cd hatchi && flutter config --enable-linux-desktop && flutter build linux
      - name: Build Go
        run: cd backend && go build -o ./server .
