name: release
on:
  push:
    branches:
      - main
    paths:
      - backend/**
      - hatchi/**
      - proto/**
permissions:
  actions: write
  contents: write
jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      # create release with zipped source code
      - name: Create New Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Beta.${{ github.run_number }}
          release_name: Beta ${{ github.run_number }}
    outputs:
      upload_url: ${{ steps.create-new-release.outputs.upload_url }}
  linux_build:
    name: Build Linux Release
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Download Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.10'
      - name: Download Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.19.0'
      - name: Download Protoc Compiler
        run: sudo apt-get install -y protobuf-compiler
      - name: Compile Proto
        run: export HATCHI_HOME=$GITHUB_WORKSPACE && ./proto/compile
        shell: bash
      - name: Build Flutter
        run: "sudo apt-get update -y\nsudo apt-get install -y ninja-build libgtk-3-dev\ncd hatchi && flutter config --enable-linux-desktop && flutter build linux \n"
      - name: Build Go
        run: cd backend && go build -o ./server .
      - name: Zip Release
        # attach backend and zip for release
        run: |
          cp -r backend hatchi/build/linux/x64/release/bundle
          cd hatchi/build/linux/x64/release/bundle && zip -r ./release.zip .
      - name: Upload To Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: hatchi/build/linux/x64/release/bundle/release.zip
          asset_name: hatchi.0.0.${{github.run_number}}.zip
          asset_content_type: application/zip

# TODO: build for windows and macOS
